#ifndef CONFIG_H_
#define CONFIG_H_

#define RGB_BUILTIN 21

// #define DEBUG_MODE
#define DEADZONE 40
#define DEFAULT_TRIGGER 80
#define DEFAULT_RESET 60

#define ADC_BYTE_SIZE 2
#define LP_BASE_ADDRESS 0
#define HP_BASE_ADDRESS LP_BASE_ADDRESS + pincount * ADC_BYTE_SIZE
#define RT_TRIGGER_ADDRESS HP_BASE_ADDRESS + pincount * ADC_BYTE_SIZE
#define RT_RESET_ADDRESS RT_TRIGGER_ADDRESS + pincount * ADC_BYTE_SIZE

#endif  /* CONFIG_H_ */



